### ISSUE TITLE
BiomeFogMap config does not work

### ISSUE THREAD

**Issue by FusionSwarly** [shizotoaster/foglooksmodernnow#5]
Copying and pasting the example config for BiomeFogMap will cause an error during loading.

[20Feb2024 08:49:50.439] [modloading-worker-0/INFO] [net.shizotoaster.foglooksmodernnow.FogLooksModernNow/]: Initialized Config Values
[20Feb2024 08:49:50.439] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: Index 0 out of bounds for length 0
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4692/0x00000008019a5538@281a9532
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at TRANSFORMER/foglooksmodernnow@1.2.1/net.shizotoaster.foglooksmodernnow.config.FogLooksGoodNowConfig.getDensityConfigs(FogLooksGoodNowConfig.java:57)
	at TRANSFORMER/foglooksmodernnow@1.2.1/net.shizotoaster.foglooksmodernnow.client.FogManager.initializeConfig(FogManager.java:91)
	at TRANSFORMER/foglooksmodernnow@1.2.1/net.shizotoaster.foglooksmodernnow.FogLooksModernNow.lambda$onConfigLoad$0(FogLooksModernNow.java:34)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at TRANSFORMER/foglooksmodernnow@1.2.1/net.shizotoaster.foglooksmodernnow.FogLooksModernNow.onConfigLoad(FogLooksModernNow.java:34)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/javafmllanguage@1.20.1-47.1.3/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:153)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:153)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.fml.core.ModStateProvider.lambda$new$1(ModStateProvider.java:67)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:66)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217)

**Comment by davidjjung** [comment]
would like to second this--this issue is actually a carry-over from the original version, according to a [similar issue](https://github.com/birsy/Fog-Looks-Good-Now/issues/13). This can be fixed by changing one line in the config class (which unfortunately cannot be done from just a mod user/modpack maker perspective)--I just tested it out in a dev environment to see. Incidentally, fog color still doesn't change even with the fix (EDIT: just saw in the config that it's meant to change _cave fog color_, not normal biome fog. my mistake! i think the config does everything it advertises), but at the very least one can control the fog render on a biome-per-biome basis. I'll try making a PR and see if that goes anywhere :]
